name: Getting serets within Actions

on:
  push:
    branches:
      - main

jobs:
  get-repo-secret: 
    runs-on: ubuntu-latest
    steps: 
      - name: Retrieve secret 
        env: 
          super_secret: ${{ secrets.MY_SECRET }}
        run: |
          if [[ $super_secret == "repo secret" ]]; then 
            echo "successfully got the repo value"
          fi
  get-env-secret: 
    environment: dev
    runs-on: ubuntu-latest
    steps: 
      - name: Retrieve secret 
        env: 
          super_secret: ${{ secrets.MY_SECRET }}
        run: |
          if [[ $super_secret == "env secret" ]]; then 
            echo "successfully got the env value"
          fi